GET http://localhost:7071/api/CategoryList

###
GET http://localhost:7071/api/CategoryList/2

###
GET http://localhost:7071/api/ProductList?CategoryId=1

###
POST http://localhost:7071/api/AddProduct
Content-Type: application/json

{
    "Name": "Test product",
    "Color": "blue",
    "StandardCost": 100,
    "ListPrice": 200,
    "Size": "M",
    "Weight": 1.23,
    "ProductCategoryID": 40
}


###
GET http://localhost:7071/api/ProductSalesSummary/991

###